///////////////////////////////////////////////////////////////////////////////
// ModuleSafety.h
#pragma once

#include "MotionControlInterfaces.h"
#include "SafetyController.h"
#include "SafetyStateMachine.h"
#include "TcFileAccessInterfaces.h"
#include "tinyxml2.h"
#include "TcRtInterfaces.h"

using namespace tinyxml2;

class CModuleSafety 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
	, public ISafetyInterface
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_MotionControlCModuleSafety)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CModuleSafety();
	virtual	~CModuleSafety();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

	// ISafetyInterface
	virtual HRESULT TCOMAPI EnterRecoveryState();
	virtual HRESULT TCOMAPI LeaveRecoveryState();

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	// Xml related variables
	UINT ReadFile(PCCH szFileNameRead, char* contents, UINT max_read);
	HRESULT ParseFileAndAssignValue(const char* xml_axis_group, const char* xml_spindle);
	ITcFileAccessPtr m_spFileAccess;
	PCCH m_AxisGroupConfigPath = "%TC_RESOURCEPATH%AxisGroupSafetyParameter.xml";
	PCCH m_SpindleConfigPath = "%TC_RESOURCEPATH%SpindleSafetyParameter.xml";

	// Other module RPC
	bool m_IsRpcReady = false;
	bool InitializeOtherModuleRpc();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	ModuleSafetyParameter m_Parameter;
	ModuleSafetyInputs m_Inputs;
	ModuleSafetyOutputs m_Outputs;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
	IMotionControlInterfacePtr m_spMainModule_Interface;
///</AutoGeneratedContent>

	CCriticalSectionInstance m_csInstance;
	CSafetyController m_SafetyController;
	SafetyStateMachine* m_SafetyStateMachine;
};
