///////////////////////////////////////////////////////////////////////////////
// MotionControlServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_MotionControl = 0x3F000000;
#define SRVNAME_MOTIONCONTROL "MotionControl"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_MotionControlCMotionControl = {0x73d79b9f,0xfc12,0x4c59,{0x97,0x3c,0x7e,0x93,0x7a,0x98,0x2d,0xda}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_MotionControlParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_54E74FBE_0A82_440E_8829_BF368D27C93C_INCLUDED_)
#define _TC_TYPE_54E74FBE_0A82_440E_8829_BF368D27C93C_INCLUDED_
typedef struct _MotionCommand
{
	double pos[5];
	double vel[5];
	double acc[5];
	double kp[5];
	double kv[5];
	double ka[5];
	SHORT opMode[5];
	unsigned char reserved1[2];
	ULONG commandIndex;
} MotionCommand, *PMotionCommand;
#endif // !defined(_TC_TYPE_54E74FBE_0A82_440E_8829_BF368D27C93C_INCLUDED_)

#if !defined(_TC_TYPE_1EADE0BF_0E40_47AC_BFA2_37826BC9272D_INCLUDED_)
#define _TC_TYPE_1EADE0BF_0E40_47AC_BFA2_37826BC9272D_INCLUDED_
typedef struct _MotionControlInfo
{
	SHORT AbsEncDir;
	unsigned char reserved1[2];
	LONG AbsEncRes;
	double RatedCurrent;
	double RatedTorque;
	SHORT TorDir;
	unsigned char reserved2[2];
	LONG AbsZeroPos;
	LONG PosUpperLimit;
	LONG PosLowerLimit;
	double ReductionRatio;
	SHORT TorPdoMax;
	bool AbsEncType;
	unsigned char reserved3[5];
} MotionControlInfo, *PMotionControlInfo;
#endif // !defined(_TC_TYPE_1EADE0BF_0E40_47AC_BFA2_37826BC9272D_INCLUDED_)

#if !defined(_TC_TYPE_BBFCA707_D69C_480D_A79E_A9CA0E101CE3_INCLUDED_)
#define _TC_TYPE_BBFCA707_D69C_480D_A79E_A9CA0E101CE3_INCLUDED_
typedef struct _DriverInput
{
	USHORT StatusWord;
	unsigned char reserved1[2];
	LONG ActualIncPos;
	LONG ActualAbsPos;
	SHORT ActualTor;
	unsigned char reserved2[2];
	LONG ActualVel;
	USHORT ErrorCode;
	USHORT WarningCode;
	SHORT DigitalInput_1;
	unsigned char reserved3[2];
} DriverInput, *PDriverInput;
#endif // !defined(_TC_TYPE_BBFCA707_D69C_480D_A79E_A9CA0E101CE3_INCLUDED_)

#if !defined(_TC_TYPE_EC6E6204_239F_476C_8280_1984DD110714_INCLUDED_)
#define _TC_TYPE_EC6E6204_239F_476C_8280_1984DD110714_INCLUDED_
typedef struct _DriverOutput
{
	USHORT ControlWord;
	unsigned char reserved1[2];
	LONG TargetPosition;
	SHORT TargetTorque;
	unsigned char reserved2[2];
	LONG TargetVelocity;
} DriverOutput, *PDriverOutput;
#endif // !defined(_TC_TYPE_EC6E6204_239F_476C_8280_1984DD110714_INCLUDED_)

#if !defined(_TC_TYPE_F68E0FAF_5F38_45CF_83DF_B0AD64425C4B_INCLUDED_)
#define _TC_TYPE_F68E0FAF_5F38_45CF_83DF_B0AD64425C4B_INCLUDED_
enum SystemState : SHORT {
	eIdle = 0,
	eInitialization = 1,
	eDisabled = 2,
	eStandby = 3,
	eMoving = 4,
	eHandwheel = 5,
	eFault = 6,
	eEmergency = 7,
	eTest = 8
};
#endif // !defined(_TC_TYPE_F68E0FAF_5F38_45CF_83DF_B0AD64425C4B_INCLUDED_)

#if !defined(_TC_TYPE_EAB6EE99_3542_4A5E_883F_595E396D7A5C_INCLUDED_)
#define _TC_TYPE_EAB6EE99_3542_4A5E_883F_595E396D7A5C_INCLUDED_
typedef struct _PanelInfo
{
	bool ServoOn;
	bool AxisEnable[5];
	unsigned char reserved1[2];
	double AxisRatio;
	double Handwheel_dPos[5];
	bool Estop;
	unsigned char reserved2[7];
} PanelInfo, *PPanelInfo;
#endif // !defined(_TC_TYPE_EAB6EE99_3542_4A5E_883F_595E396D7A5C_INCLUDED_)

#if !defined(_TC_TYPE_0BC470A9_F028_4F4D_AC8A_4649A0A47B5B_INCLUDED_)
#define _TC_TYPE_0BC470A9_F028_4F4D_AC8A_4649A0A47B5B_INCLUDED_
enum OpMode : SHORT {
	CSP = 0,
	CST = 1,
	CSV = 2
};
#endif // !defined(_TC_TYPE_0BC470A9_F028_4F4D_AC8A_4649A0A47B5B_INCLUDED_)

#if !defined(_TC_TYPE_F1A73FE8_38D8_4F10_8AF2_2FFE7F01D141_INCLUDED_)
#define _TC_TYPE_F1A73FE8_38D8_4F10_8AF2_2FFE7F01D141_INCLUDED_
enum DriverState : USHORT {
	eNotReadyForPowerUp = 0,
	eShutDownError = 8192,
	eLogicReadyForPowerOn = 16384,
	ePowerStageLocked = 32768,
	eReadyToOperate = 49152
};
#endif // !defined(_TC_TYPE_F1A73FE8_38D8_4F10_8AF2_2FFE7F01D141_INCLUDED_)

#if !defined(_TC_TYPE_FB1829E7_CB1A_44B8_8E95_8BCEBED39FE6_INCLUDED_)
#define _TC_TYPE_FB1829E7_CB1A_44B8_8E95_8BCEBED39FE6_INCLUDED_
enum MasterControlWord : USHORT {
	eHaltDrive = 0,
	eRestartDrive = 8192,
	eDriveOff = 24576,
	eDriveOn_CSP = 57344,
	eDriveOn_CST = 57600,
	eDriveOn_CSV = 57856
};
#endif // !defined(_TC_TYPE_FB1829E7_CB1A_44B8_8E95_8BCEBED39FE6_INCLUDED_)

typedef struct _MotionControlParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} MotionControlParameter, *PMotionControlParameter;

typedef struct _MotionControlInputs
{
	MotionCommand CommandData;
	MotionControlInfo MotionCtrlParam[4][1];
	DriverInput DriverInputs[4][1];
	PanelInfo PanelInformation;
	bool mockButton[10];
	unsigned char reserved1[6];
	double TestInputs[20];
} MotionControlInputs, *PMotionControlInputs;

typedef struct _MotionControlOutputs
{
	DriverOutput DriverOutputs[4][1];
	double TestOutputs[20];
} MotionControlOutputs, *PMotionControlOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_MotionControlInputs 0
#define ADI_MotionControlOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
