///////////////////////////////////////////////////////////////////////////////
// MotionControlClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "MotionControlClassFactory.h"
#include "MotionControlServices.h"
#include "MotionControlVersion.h"
#include "MotionControl.h"

BEGIN_CLASS_MAP(CMotionControlClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_MotionControlCMotionControl, SRVNAME_MOTIONCONTROL "!CMotionControl", CMotionControl)
///</AutoGeneratedContent>
END_CLASS_MAP()

CMotionControlClassFactory::CMotionControlClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_MOTIONCONTROL));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(MotionControl));
#endif //defined(TCDBG_UNIT_VERSION)
}

