///////////////////////////////////////////////////////////////////////////////
// MotionControlServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_MotionControl = 0x3F000000;
#define SRVNAME_MOTIONCONTROL "MotionControl"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_MotionControlCMotionControl = {0x73d79b9f,0xfc12,0x4c59,{0x97,0x3c,0x7e,0x93,0x7a,0x98,0x2d,0xda}};
const CTCID CID_MotionControlCModuleSpindle = {0x3754dd69,0xaf00,0x4776,{0xa5,0x3a,0x88,0x1a,0x1f,0xc8,0x34,0x36}};
const CTCID CID_MotionControlCModuleSafety = {0xb956c8e0,0x7a9e,0x4b80,{0xb4,0xb5,0xcb,0x85,0xd7,0xfb,0x7a,0xf1}};
const CTCID CID_MotionControlCModuleAxisGroup = {0xa90978e9,0xb255,0x4d60,{0xbd,0xe4,0x57,0xe1,0x76,0x17,0xbd,0x77}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_MotionControlParameter = 0x00000001;
const PTCID PID_MotionControlPLC_PanelProcess = 0x00000003;
const PTCID PID_MotionControlModuleSpindle_Interface = 0x00000004;
const PTCID PID_MotionControlModuleAxisGroup_Interface = 0x00000002;
const PTCID PID_MotionControlPLC_ScopeProcess = 0x00000005;
const PTCID PID_ModuleSpindleParameter = 0x00000001;
const PTCID PID_ModuleSafetyParameter = 0x00000001;
const PTCID PID_ModuleSafetyMainModule_Interface = 0x00000002;
const PTCID PID_ModuleAxisGroupParameter = 0x00000001;
const PTCID PID_ModuleAxisGroupPLC_SoeProcess = 0x00000002;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_EE32EC38_3CFD_4D8B_9EB4_C1E6E69C354B_INCLUDED_)
#define _TC_TYPE_EE32EC38_3CFD_4D8B_9EB4_C1E6E69C354B_INCLUDED_
typedef struct _MotionControlInfo
{
	SHORT AbsEncDir;
	unsigned char reserved1[2];
	LONG AbsEncRes;
	double RatedCurrent;
	double RatedTorque;
	SHORT TorDir;
	unsigned char reserved2[2];
	LONG AbsZeroPos;
	double TransmissionRatio;
	SHORT TorPdoMax;
	SHORT AdditiveTorque;
	SHORT MoveType;
	SHORT DriverType;
	bool Exposed;
	unsigned char reserved3[7];
} MotionControlInfo, *PMotionControlInfo;
#endif // !defined(_TC_TYPE_EE32EC38_3CFD_4D8B_9EB4_C1E6E69C354B_INCLUDED_)

#if !defined(_TC_TYPE_91114EB3_9644_4864_867E_7C4ACBF08BE8_INCLUDED_)
#define _TC_TYPE_91114EB3_9644_4864_867E_7C4ACBF08BE8_INCLUDED_
typedef struct _DriverInput
{
	USHORT StatusWord;
	unsigned char reserved1[2];
	LONG ActualAbsPos;
	SHORT ActualTor;
	unsigned char reserved2[2];
	LONG ActualVel;
	SHORT ErrorCode;
	SHORT WarningCode;
	SHORT DigitalInput_1;
	char ActualOpMode;
	unsigned char reserved3;
} DriverInput, *PDriverInput;
#endif // !defined(_TC_TYPE_91114EB3_9644_4864_867E_7C4ACBF08BE8_INCLUDED_)

#if !defined(_TC_TYPE_D92A0736_9D45_45DD_BCE4_6585EAB67921_INCLUDED_)
#define _TC_TYPE_D92A0736_9D45_45DD_BCE4_6585EAB67921_INCLUDED_
#pragma pack(push,1)
typedef struct _DriverOutput
{
	USHORT ControlWord;
	unsigned char reserved1[2];
	LONG TargetPosition;
	SHORT TargetTorque;
	unsigned char reserved2[2];
	LONG TargetVelocity;
	char OperationMode;
	SHORT AdditiveTorque;
} DriverOutput, *PDriverOutput;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_D92A0736_9D45_45DD_BCE4_6585EAB67921_INCLUDED_)

#if !defined(_TC_TYPE_9B565FBB_17C1_45CE_82EA_7792EFF0874B_INCLUDED_)
#define _TC_TYPE_9B565FBB_17C1_45CE_82EA_7792EFF0874B_INCLUDED_
enum SystemState : SHORT {
	eIdle = 0,
	eDisabled = 1,
	ePreStandby = 2,
	eStandby = 3,
	eManual = 4,
	eBuffering = 5,
	eContinuousExecution = 6,
	eFault = 7,
	eTest = 8,
	eRecovery = 9
};
#endif // !defined(_TC_TYPE_9B565FBB_17C1_45CE_82EA_7792EFF0874B_INCLUDED_)

#if !defined(_TC_TYPE_13C5ED93_554D_47D2_9A08_D46CC349EDDD_INCLUDED_)
#define _TC_TYPE_13C5ED93_554D_47D2_9A08_D46CC349EDDD_INCLUDED_
typedef struct _PanelInfo
{
	bool ServoOn;
	unsigned char reserved1;
	SHORT Handwheel_EnabledAxisNum;
	unsigned char reserved2[4];
	double Handwheel_Ratio;
	double Handwheel_dPos[5];
	SHORT Spindle_Cmd;
	bool Reset;
	bool Execute;
	unsigned char reserved3[4];
} PanelInfo, *PPanelInfo;
#endif // !defined(_TC_TYPE_13C5ED93_554D_47D2_9A08_D46CC349EDDD_INCLUDED_)

#if !defined(_TC_TYPE_75816603_8B01_41ED_9F49_1001E13236B1_INCLUDED_)
#define _TC_TYPE_75816603_8B01_41ED_9F49_1001E13236B1_INCLUDED_
enum OpMode : SHORT {
	CSP = 8,
	CSV = 9,
	CST = 10
};
#endif // !defined(_TC_TYPE_75816603_8B01_41ED_9F49_1001E13236B1_INCLUDED_)

#if !defined(_TC_TYPE_760AEB87_AF7B_4178_B0AF_C2E7472652E4_INCLUDED_)
#define _TC_TYPE_760AEB87_AF7B_4178_B0AF_C2E7472652E4_INCLUDED_
enum DriverState : USHORT {
	eNotReadyForPowerUp = 0,
	eShutDownError = 40960,
	eLogicReadyForPowerOn = 16384,
	ePowerStageLocked = 32768,
	eReadyToOperate = 49152
};
#endif // !defined(_TC_TYPE_760AEB87_AF7B_4178_B0AF_C2E7472652E4_INCLUDED_)

#if !defined(_TC_TYPE_8A0CBD64_A622_4812_96E8_6466F6FAD96D_INCLUDED_)
#define _TC_TYPE_8A0CBD64_A622_4812_96E8_6466F6FAD96D_INCLUDED_
enum MasterControlWord : USHORT {
	eHaltDrive = 0,
	eStopDrive = 1,
	eControlUnitSync = 1024,
	eRestartDrive = 8192,
	eDriveOff = 24576,
	eDriveOn_CSP = 57344,
	eDriveOn_CST = 57600,
	eDriveOn_CSV = 57856
};
#endif // !defined(_TC_TYPE_8A0CBD64_A622_4812_96E8_6466F6FAD96D_INCLUDED_)

#if !defined(_TC_TYPE_2AB905D5_7D46_411F_BE58_01268BBF5FBB_INCLUDED_)
#define _TC_TYPE_2AB905D5_7D46_411F_BE58_01268BBF5FBB_INCLUDED_
enum AxisOrder : SHORT {
	Axis_X = 1,
	Axis_Y = 2,
	Axis_Z = 3,
	Axis_A = 4,
	Axis_C = 5,
	Spindle = 6
};
#endif // !defined(_TC_TYPE_2AB905D5_7D46_411F_BE58_01268BBF5FBB_INCLUDED_)

#if !defined(_TC_TYPE_5CBC67ED_7FEB_485B_91B9_3CE3460A4A42_INCLUDED_)
#define _TC_TYPE_5CBC67ED_7FEB_485B_91B9_3CE3460A4A42_INCLUDED_
typedef struct _AxisInformation
{
	double CurrentPos;
	double CurrentVel;
	SHORT CurrentTor;
	unsigned char CurrentMode;
	unsigned char reserved1[5];
	double CommandPos;
	double CommandVel;
	SHORT CommandTor;
	SHORT CurrentStatus;
	unsigned char reserved2[4];
} AxisInformation, *PAxisInformation;
#endif // !defined(_TC_TYPE_5CBC67ED_7FEB_485B_91B9_3CE3460A4A42_INCLUDED_)

#if !defined(_TC_TYPE_8A554618_FB22_4EDD_9FCF_D053B7A70EC0_INCLUDED_)
#define _TC_TYPE_8A554618_FB22_4EDD_9FCF_D053B7A70EC0_INCLUDED_
typedef struct _InterpolationParameter
{
	double MaxVelocity;
	double MaxAcceleration;
	double MaxJerk;
	double CycleTime;
	double Tolerance;
} InterpolationParameter, *PInterpolationParameter;
#endif // !defined(_TC_TYPE_8A554618_FB22_4EDD_9FCF_D053B7A70EC0_INCLUDED_)

#if !defined(_TC_TYPE_F1F3C2D0_7F5A_4C6C_A483_0A5FA097C058_INCLUDED_)
#define _TC_TYPE_F1F3C2D0_7F5A_4C6C_A483_0A5FA097C058_INCLUDED_
enum ControlWordGeneral : SHORT {
	eDisableVoltage = 0,
	eQuickStop = 2,
	eShutdown = 6,
	eDisableOperation = 7,
	eSwitchOn = 7,
	eEnableOperation = 15,
	eFaultReset = 128
};
#endif // !defined(_TC_TYPE_F1F3C2D0_7F5A_4C6C_A483_0A5FA097C058_INCLUDED_)

#if !defined(_TC_TYPE_6B6236F7_1899_4101_9CCB_762E700EF682_INCLUDED_)
#define _TC_TYPE_6B6236F7_1899_4101_9CCB_762E700EF682_INCLUDED_
enum DriverStateGeneral : SHORT {
	eNotReadyToSwitchOn = 0,
	eSwitchOnDisabled = 64,
	eReadyToSwitchOn = 33,
	eSwitchedOn = 35,
	eOperationEnabled = 39,
	eQuickStopActive = 7,
	eFaultReactionActive = 15,
	eDriverFault = 8,
	eQuickStopBit = 32
};
#endif // !defined(_TC_TYPE_6B6236F7_1899_4101_9CCB_762E700EF682_INCLUDED_)

#if !defined(_TC_TYPE_6C52FF3C_3F1E_4DF4_B88E_56EAE4037B12_INCLUDED_)
#define _TC_TYPE_6C52FF3C_3F1E_4DF4_B88E_56EAE4037B12_INCLUDED_
typedef struct _MetaData
{
	unsigned char CommandType;
	unsigned char reserved1[3];
	ULONG SourceActionBlockIndex;
	ULONG Index;
} MetaData, *PMetaData;
#endif // !defined(_TC_TYPE_6C52FF3C_3F1E_4DF4_B88E_56EAE4037B12_INCLUDED_)

#if !defined(_TC_TYPE_2288AC91_0B91_49E2_8120_4064BEBCA6CE_INCLUDED_)
#define _TC_TYPE_2288AC91_0B91_49E2_8120_4064BEBCA6CE_INCLUDED_
typedef struct _NewMotionCommand
{
	double Pos[5];
	double Vel[5];
	double Acc[5];
	double Kp[5][5];
	double Kv[5][5];
	double Ka[5][5];
} NewMotionCommand, *PNewMotionCommand;
#endif // !defined(_TC_TYPE_2288AC91_0B91_49E2_8120_4064BEBCA6CE_INCLUDED_)

#if !defined(_TC_TYPE_0C8C736F_2009_4A9B_BA79_A373A15B7252_INCLUDED_)
#define _TC_TYPE_0C8C736F_2009_4A9B_BA79_A373A15B7252_INCLUDED_
typedef struct _OtherCommand
{
	ULONG CommandFunction;
	unsigned char reserved1[4];
	double Data;
} OtherCommand, *POtherCommand;
#endif // !defined(_TC_TYPE_0C8C736F_2009_4A9B_BA79_A373A15B7252_INCLUDED_)

#if !defined(_TC_TYPE_1ED6E5CA_471D_4209_B5E6_F93D33BD9C80_INCLUDED_)
#define _TC_TYPE_1ED6E5CA_471D_4209_B5E6_F93D33BD9C80_INCLUDED_
typedef struct _FullCommand
{
	MetaData metaData;
	unsigned char reserved1[4];
	NewMotionCommand motionCommand;
	OtherCommand otherCommand;
} FullCommand, *PFullCommand;
#endif // !defined(_TC_TYPE_1ED6E5CA_471D_4209_B5E6_F93D33BD9C80_INCLUDED_)

#if !defined(_TC_TYPE_1EE09E32_CE03_49CF_9231_332125EF3F61_INCLUDED_)
#define _TC_TYPE_1EE09E32_CE03_49CF_9231_332125EF3F61_INCLUDED_
enum CommandType : SHORT {
	eMotion = 1,
	eOther = 4,
	eSignalFinalized = 5,
	eNone = 0,
	eSingleAxisX = 10,
	eSingleAxisY = 11,
	eSingleAxisZ = 12,
	eSingleAxisA = 13,
	eSingleAxisC = 14
};
#endif // !defined(_TC_TYPE_1EE09E32_CE03_49CF_9231_332125EF3F61_INCLUDED_)

#if !defined(_TC_TYPE_9C29111D_2AB9_43BB_ACE9_11CADBF59920_INCLUDED_)
#define _TC_TYPE_9C29111D_2AB9_43BB_ACE9_11CADBF59920_INCLUDED_
typedef struct _SpindleRot
{
	double TargetVel;
} SpindleRot, *PSpindleRot;
#endif // !defined(_TC_TYPE_9C29111D_2AB9_43BB_ACE9_11CADBF59920_INCLUDED_)

#if !defined(_TC_TYPE_9689CD0C_E531_4687_BB83_6D4BB1F2F1CD_INCLUDED_)
#define _TC_TYPE_9689CD0C_E531_4687_BB83_6D4BB1F2F1CD_INCLUDED_
typedef struct _SpindleVelLimit
{
	double MaxVel;
	double MaxAcc;
	double MaxJerk;
} SpindleVelLimit, *PSpindleVelLimit;
#endif // !defined(_TC_TYPE_9689CD0C_E531_4687_BB83_6D4BB1F2F1CD_INCLUDED_)

#if !defined(_TC_TYPE_BEAC0974_F61C_4504_BEF4_0C5C6361CD2E_INCLUDED_)
#define _TC_TYPE_BEAC0974_F61C_4504_BEF4_0C5C6361CD2E_INCLUDED_
typedef struct _SpindlePosition
{
	double TargetPos;
	double TargetVel;
} SpindlePosition, *PSpindlePosition;
#endif // !defined(_TC_TYPE_BEAC0974_F61C_4504_BEF4_0C5C6361CD2E_INCLUDED_)

#if !defined(_TC_TYPE_77803924_0147_4DB7_B733_98772013DAE4_INCLUDED_)
#define _TC_TYPE_77803924_0147_4DB7_B733_98772013DAE4_INCLUDED_
typedef struct _SpindleCommand
{
	OpMode ModeOfOperation;
	unsigned char reserved1[6];
	double TargetPos;
	double TargetVel;
} SpindleCommand, *PSpindleCommand;
#endif // !defined(_TC_TYPE_77803924_0147_4DB7_B733_98772013DAE4_INCLUDED_)

#if !defined(_TC_TYPE_F83D71B3_EDF7_41E0_B7AD_30BCAEB092E9_INCLUDED_)
#define _TC_TYPE_F83D71B3_EDF7_41E0_B7AD_30BCAEB092E9_INCLUDED_
enum AxisGroupState : SHORT {
	eAxisGroupIdle = 0,
	eAxisGroupInitialization = 1,
	eAxisGroupDisabled = 2,
	eAxisGroupPreStandby = 3,
	eAxisGroupStandby = 4,
	eAxisGroupManualMoving = 5,
	eAxisGroupPreContinuousMoving = 6,
	eAxisGroupContinuousMoving = 7,
	eAxisGroupLimitViolation = 8,
	eAxisGroupEmergency = 9,
	eAxisGroupFault = 10,
	eAxisGroupRecovery = 11,
	eAxisGroupTest = 12
};
#endif // !defined(_TC_TYPE_F83D71B3_EDF7_41E0_B7AD_30BCAEB092E9_INCLUDED_)

#if !defined(_TC_TYPE_DF678954_0CC7_4B57_A830_AD3AD6D5FFCE_INCLUDED_)
#define _TC_TYPE_DF678954_0CC7_4B57_A830_AD3AD6D5FFCE_INCLUDED_
enum SpindleState : SHORT {
	eSpindleIdle = 0,
	eSpindleInitialization = 1,
	eSpindleDisabled = 2,
	eSpindleEnable = 3,
	eSpindlePreMoving = 4,
	eSpindleRotating = 5,
	eSpindlePositioning = 6,
	eSpindlePostMoving = 7,
	eSpindleEmergency = 8,
	eSpindleFault = 9,
	eSpindleTest = 10
};
#endif // !defined(_TC_TYPE_DF678954_0CC7_4B57_A830_AD3AD6D5FFCE_INCLUDED_)

#if !defined(_TC_TYPE_79339E68_6E3A_41AF_8D1F_A9030AA0D6D8_INCLUDED_)
#define _TC_TYPE_79339E68_6E3A_41AF_8D1F_A9030AA0D6D8_INCLUDED_
enum CommandFunction : SHORT {
	eSpindle = 500,
	eM30 = 1000,
	eSetTool = 2
};
#endif // !defined(_TC_TYPE_79339E68_6E3A_41AF_8D1F_A9030AA0D6D8_INCLUDED_)

#if !defined(_TC_TYPE_915A7E92_BCA1_44CD_B0B0_09766308F5C5_INCLUDED_)
#define _TC_TYPE_915A7E92_BCA1_44CD_B0B0_09766308F5C5_INCLUDED_
enum AxisGroupErrorType : SHORT {
	eAxisGroupErrorNone = 0,
	eAxisGroupErrorGeneral = 1,
	eAxisGroupErrorPosOver = 2,
	eAxisGroupErrorVelOver = 3,
	eAxisGroupErrorEmergency = 4
};
#endif // !defined(_TC_TYPE_915A7E92_BCA1_44CD_B0B0_09766308F5C5_INCLUDED_)

#if !defined(_TC_TYPE_D08D34EA_915E_41E1_AC0D_7DBB1E98D59A_INCLUDED_)
#define _TC_TYPE_D08D34EA_915E_41E1_AC0D_7DBB1E98D59A_INCLUDED_
enum SpindleErrorType : SHORT {
	eSpindleErrorNone = 0,
	eSpindleErrorGeneral = 1,
	eSpindleErrorPosOver = 2,
	eSpindleErrorVelOver = 3,
	eSpindleErrorEmergency = 4
};
#endif // !defined(_TC_TYPE_D08D34EA_915E_41E1_AC0D_7DBB1E98D59A_INCLUDED_)

#if !defined(_TC_TYPE_027C9C33_01AD_4189_9A4E_B1392F3124FB_INCLUDED_)
#define _TC_TYPE_027C9C33_01AD_4189_9A4E_B1392F3124FB_INCLUDED_
enum SafetyState : SHORT {
	eSafetyStateNormal = 0,
	eSafetyStateWarning = 1,
	eSafetyStateEmergency = 2,
	eSafetyStateFault = 3,
	eSafetyStateRecovery = 4
};
#endif // !defined(_TC_TYPE_027C9C33_01AD_4189_9A4E_B1392F3124FB_INCLUDED_)

#if !defined(_TC_TYPE_B90EEFBB_BDE8_47C4_97D9_8F8B35025DE9_INCLUDED_)
#define _TC_TYPE_B90EEFBB_BDE8_47C4_97D9_8F8B35025DE9_INCLUDED_
typedef struct _SafetyParameter
{
	double PosUpperLimit;
	double PosLowerLimit;
	double MaxVelocity;
	double MaxAcceleration;
	double FollowingError;
	SHORT PositiveHardBit;
	SHORT NegativeHardBit;
	bool IsGantry;
	unsigned char reserved1[3];
	double GantryDeviationTolerance;
} SafetyParameter, *PSafetyParameter;
#endif // !defined(_TC_TYPE_B90EEFBB_BDE8_47C4_97D9_8F8B35025DE9_INCLUDED_)

#if !defined(_TC_TYPE_85615354_18AB_4F2D_A42C_B832F67F7D5F_INCLUDED_)
#define _TC_TYPE_85615354_18AB_4F2D_A42C_B832F67F7D5F_INCLUDED_
typedef struct _AxisGroupInformation
{
	AxisInformation SingleAxisInformation[6];
	double GantryDeviation;
} AxisGroupInformation, *PAxisGroupInformation;
#endif // !defined(_TC_TYPE_85615354_18AB_4F2D_A42C_B832F67F7D5F_INCLUDED_)

typedef struct _MotionControlInputs
{
	PanelInfo PanelInformation;
	FullCommand CommandInput[1024];
	ULONG CommandWriteIndex;
	OTCID OidPanelProcess;
	ULONG ErrorCode;
	OTCID OidScopeProcess;
} MotionControlInputs, *PMotionControlInputs;

typedef struct _MotionControlOutputs
{
	ULONG CommandReadIndex;
	SystemState MainState;
	unsigned char reserved1[2];
	struct {
		SHORT SelectedAxis;
		unsigned char reserved1[6];
		double MovingCommand[5];
	} ManualMovingCommand;
	FullCommand ContinuousMovingCommand;
} MotionControlOutputs, *PMotionControlOutputs;

typedef struct _ModuleSpindleParameter
{
	MotionControlInfo SpindleDriverParam;
	InterpolationParameter SpindleInterpolationParam;
} ModuleSpindleParameter, *PModuleSpindleParameter;

typedef struct _ModuleSpindleInputs
{
	DriverInput SpindleInput;
	double SpindleTestInputs[20];
} ModuleSpindleInputs, *PModuleSpindleInputs;

#pragma pack(push,1)
typedef struct _ModuleSpindleOutputs
{
	DriverOutput SpindleOutput;
	unsigned char reserved1;
	SpindleState StateSpindle;
	unsigned char reserved2[2];
	AxisInformation SpindleInfo;
} ModuleSpindleOutputs, *PModuleSpindleOutputs;
#pragma pack(pop)

typedef struct _ModuleSafetyParameter
{
	SafetyParameter SafetyParameterAxisGroup[6];
	SafetyParameter SafetyParameterSpindle;
	SHORT ActualAxisNum;
	SHORT ActualDriverNum;
	SHORT DriverNumPerAxis[5];
	unsigned char reserved1[2];
} ModuleSafetyParameter, *PModuleSafetyParameter;

typedef struct _ModuleSafetyInputs
{
	struct {
		AxisGroupInformation AxisGroupInfo;
		AxisInformation SpindleInfo;
		AxisGroupState StateAxisGroup;
		SpindleState StateSpindle;
		SHORT AxisGroupDigitalInput[6];
	} DiagnosticInfo;
} ModuleSafetyInputs, *PModuleSafetyInputs;

typedef struct _ModuleSafetyOutputs
{
	ULONG ErrorCode;
	SafetyState SafetyStatus;
	unsigned char reserved1[2];
} ModuleSafetyOutputs, *PModuleSafetyOutputs;

typedef struct _ModuleAxisGroupParameter
{
	MotionControlInfo DriverParameter[10];
	InterpolationParameter AxisGroupInterpolationParam[10];
	SHORT ActualAxisNum;
	SHORT TotalDriverNum;
	SHORT DriverNumPerAxis[5];
	unsigned char reserved1[2];
} ModuleAxisGroupParameter, *PModuleAxisGroupParameter;

typedef struct _ModuleAxisGroupInputs
{
	OTCID OidSoEProcess;
	DriverInput AxisInputs[10];
	unsigned char reserved1[4];
	double TestInputs[20];
	FullCommand ContinuousMovingCommand;
	struct {
		SHORT SelectedAxis;
		unsigned char reserved1[6];
		double MovingCommand[5];
	} ManualMovingCommand;
} ModuleAxisGroupInputs, *PModuleAxisGroupInputs;

#pragma pack(push,1)
typedef struct _ModuleAxisGroupOutputs
{
	DriverOutput AxisOutputs[10];
	AxisGroupState StateAxisGroup;
	AxisGroupInformation AxisGroupInfo;
} ModuleAxisGroupOutputs, *PModuleAxisGroupOutputs;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_MotionControlInputs 0
#define ADI_MotionControlOutputs 1
#define ADI_ModuleSpindleInputs 0
#define ADI_ModuleSpindleOutputs 1
#define ADI_ModuleSafetyInputs 0
#define ADI_ModuleSafetyOutputs 1
#define ADI_ModuleAxisGroupInputs 0
#define ADI_ModuleAxisGroupOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_4D6E4DE6_92E2_4E0E_9440_3F5F63A1A390_INCLUDED_)
#define _TC_IID_4D6E4DE6_92E2_4E0E_9440_3F5F63A1A390_INCLUDED_
TCOM_DECL_INTERFACE("4d6e4de6-92e2-4e0e-9440-3f5f63a1a390", IMotionControlInterface)
#endif // !defined(_TC_IID_4D6E4DE6_92E2_4E0E_9440_3F5F63A1A390_INCLUDED_)

#if !defined(_TC_IID_83716734_5838_48EA_8367_90CBAD873477_INCLUDED_)
#define _TC_IID_83716734_5838_48EA_8367_90CBAD873477_INCLUDED_
TCOM_DECL_INTERFACE("83716734-5838-48ea-8367-90cbad873477", ISoEProcess)
#endif // !defined(_TC_IID_83716734_5838_48EA_8367_90CBAD873477_INCLUDED_)

#if !defined(_TC_IID_8912121D_6A99_4443_9716_8F2A85D3B99E_INCLUDED_)
#define _TC_IID_8912121D_6A99_4443_9716_8F2A85D3B99E_INCLUDED_
TCOM_DECL_INTERFACE("8912121d-6a99-4443-9716-8f2a85d3b99e", IPanelProcess)
#endif // !defined(_TC_IID_8912121D_6A99_4443_9716_8F2A85D3B99E_INCLUDED_)

#if !defined(_TC_IID_A5B190D2_781F_49A4_9D2B_66AD8519040D_INCLUDED_)
#define _TC_IID_A5B190D2_781F_49A4_9D2B_66AD8519040D_INCLUDED_
TCOM_DECL_INTERFACE("a5b190d2-781f-49a4-9d2b-66ad8519040d", ISpindleInterface)
#endif // !defined(_TC_IID_A5B190D2_781F_49A4_9D2B_66AD8519040D_INCLUDED_)

#if !defined(_TC_IID_92B58E62_00D3_492F_A964_14316BC3B3CF_INCLUDED_)
#define _TC_IID_92B58E62_00D3_492F_A964_14316BC3B3CF_INCLUDED_
TCOM_DECL_INTERFACE("92b58e62-00d3-492f-a964-14316bc3b3cf", IAxisGroupInterface)
#endif // !defined(_TC_IID_92B58E62_00D3_492F_A964_14316BC3B3CF_INCLUDED_)

#if !defined(_TC_IID_DFA7B551_502B_4085_88E7_A88921AF739F_INCLUDED_)
#define _TC_IID_DFA7B551_502B_4085_88E7_A88921AF739F_INCLUDED_
TCOM_DECL_INTERFACE("dfa7b551-502b-4085-88e7-a88921af739f", ISafetyInterface)
#endif // !defined(_TC_IID_DFA7B551_502B_4085_88E7_A88921AF739F_INCLUDED_)

#if !defined(_TC_IID_ECB4C8CD_4DFF_4EA0_97A5_D5D0C67E798D_INCLUDED_)
#define _TC_IID_ECB4C8CD_4DFF_4EA0_97A5_D5D0C67E798D_INCLUDED_
TCOM_DECL_INTERFACE("ecb4c8cd-4dff-4ea0-97a5-d5d0c67e798d", IScopeProcess)
#endif // !defined(_TC_IID_ECB4C8CD_4DFF_4EA0_97A5_D5D0C67E798D_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
