///////////////////////////////////////////////////////////////////////////////
// MotionControlInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "MotionControlServices.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_0A661E3E_E020_43B6_B916_4725F5A024F4_INCLUDED_)
#define _TC_TYPE_0A661E3E_E020_43B6_B916_4725F5A024F4_INCLUDED_
struct __declspec(novtable) IMotionControlInterface : public ITcUnknown
{
	virtual HRESULT TCOMAPI ExecuteCommandsContinuously(SHORT n_min_data_start, SHORT& buffer_size, char op_mode)=0;
	virtual HRESULT TCOMAPI EnterRecoveryState(bool is_entered)=0;
	virtual HRESULT TCOMAPI RequestStop()=0;
};
_TCOM_SMARTPTR_TYPEDEF(IMotionControlInterface, IID_IMotionControlInterface);
#endif // !defined(_TC_TYPE_0A661E3E_E020_43B6_B916_4725F5A024F4_INCLUDED_)

#if !defined(_TC_TYPE_970DA61A_269B_41C3_8941_02F0458E1BF8_INCLUDED_)
#define _TC_TYPE_970DA61A_269B_41C3_8941_02F0458E1BF8_INCLUDED_
struct __declspec(novtable) ISoEProcess : public ITcUnknown
{
	virtual HRESULT TCOMAPI mInitialize()=0;
	virtual HRESULT TCOMAPI mReset(bool bExecute)=0;
};
_TCOM_SMARTPTR_TYPEDEF(ISoEProcess, IID_ISoEProcess);
#endif // !defined(_TC_TYPE_970DA61A_269B_41C3_8941_02F0458E1BF8_INCLUDED_)

#if !defined(_TC_TYPE_BAA6EC0B_E089_4261_B526_D49D4945A12E_INCLUDED_)
#define _TC_TYPE_BAA6EC0B_E089_4261_B526_D49D4945A12E_INCLUDED_
struct __declspec(novtable) IPanelProcess : public ITcUnknown
{
	virtual HRESULT TCOMAPI mInitialize()=0;
	virtual HRESULT TCOMAPI mFaultReset()=0;
	virtual HRESULT TCOMAPI mInput()=0;
	virtual HRESULT TCOMAPI mOutput()=0;
	virtual HRESULT TCOMAPI mHandwheelReset()=0;
};
_TCOM_SMARTPTR_TYPEDEF(IPanelProcess, IID_IPanelProcess);
#endif // !defined(_TC_TYPE_BAA6EC0B_E089_4261_B526_D49D4945A12E_INCLUDED_)

#if !defined(_TC_TYPE_CF8E28DE_CFD4_4727_86E6_C55D5891DD9F_INCLUDED_)
#define _TC_TYPE_CF8E28DE_CFD4_4727_86E6_C55D5891DD9F_INCLUDED_
struct __declspec(novtable) ISpindleInterface : public ITcUnknown
{
	virtual HRESULT TCOMAPI RequestRotating(SpindleRot RotData)=0;
	virtual HRESULT TCOMAPI RequestStop()=0;
	virtual HRESULT TCOMAPI SetVelLimit(SpindleVelLimit VelLimit)=0;
	virtual HRESULT TCOMAPI RequestPositioning(SpindlePosition PositionData)=0;
	virtual HRESULT TCOMAPI ReportCurrentState(SpindleState& curr_state)=0;
	virtual HRESULT TCOMAPI RequestSpindleEnable()=0;
	virtual HRESULT TCOMAPI IsSpindleEnable(bool& is_enable)=0;
	virtual HRESULT TCOMAPI IsSpindleMoving(bool& is_moving)=0;
};
_TCOM_SMARTPTR_TYPEDEF(ISpindleInterface, IID_ISpindleInterface);
#endif // !defined(_TC_TYPE_CF8E28DE_CFD4_4727_86E6_C55D5891DD9F_INCLUDED_)

#if !defined(_TC_TYPE_08CC0D90_8987_4A20_A338_22772737A054_INCLUDED_)
#define _TC_TYPE_08CC0D90_8987_4A20_A338_22772737A054_INCLUDED_
struct __declspec(novtable) IAxisGroupInterface : public ITcUnknown
{
	virtual HRESULT TCOMAPI ReportCurrentState(AxisGroupState& curr_state)=0;
	virtual HRESULT TCOMAPI RequestEnterHandwheel()=0;
	virtual HRESULT TCOMAPI RequestQuitHandwheel()=0;
	virtual HRESULT TCOMAPI RequestContinuousMoving()=0;
	virtual HRESULT TCOMAPI RequestStop()=0;
	virtual HRESULT TCOMAPI RequestAxisGroupEnable()=0;
	virtual HRESULT TCOMAPI RequestAxisGroupDisable()=0;
	virtual HRESULT TCOMAPI RequestReset()=0;
	virtual HRESULT TCOMAPI RequestRecovery(bool is_entered)=0;
	virtual HRESULT TCOMAPI RequestChangeOpMode(OpMode mode)=0;
	virtual HRESULT TCOMAPI IsAxisGroupStandby(bool& is_standby)=0;
	virtual HRESULT TCOMAPI IsAxisGroupMoving(bool& is_moving)=0;
	virtual HRESULT TCOMAPI IsAxisGroupOpModeSwitched(bool& is_switched)=0;
	virtual HRESULT TCOMAPI IsAxisGroupDisabled(bool& is_disabled)=0;
	virtual HRESULT TCOMAPI IsAxisGroupManualMoving(bool& is_manual)=0;
};
_TCOM_SMARTPTR_TYPEDEF(IAxisGroupInterface, IID_IAxisGroupInterface);
#endif // !defined(_TC_TYPE_08CC0D90_8987_4A20_A338_22772737A054_INCLUDED_)

///</AutoGeneratedContent>
