///////////////////////////////////////////////////////////////////////////////
// MotionControlInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "MotionControlServices.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_75F6F238_A022_446E_8F56_58206FCA8931_INCLUDED_)
#define _TC_TYPE_75F6F238_A022_446E_8F56_58206FCA8931_INCLUDED_
struct __declspec(novtable) InterfaceRPC : public ITcUnknown
{
	virtual HRESULT TCOMAPI ExecuteCommandsContinuously(SHORT n_min_data_start, SHORT& buffer_size)=0;
	virtual HRESULT TCOMAPI EnterRecoveryState(bool b_Enter)=0;
};
_TCOM_SMARTPTR_TYPEDEF(InterfaceRPC, IID_InterfaceRPC);
#endif // !defined(_TC_TYPE_75F6F238_A022_446E_8F56_58206FCA8931_INCLUDED_)

#if !defined(_TC_TYPE_970DA61A_269B_41C3_8941_02F0458E1BF8_INCLUDED_)
#define _TC_TYPE_970DA61A_269B_41C3_8941_02F0458E1BF8_INCLUDED_
struct __declspec(novtable) ISoEProcess : public ITcUnknown
{
	virtual HRESULT TCOMAPI mInitialize()=0;
	virtual HRESULT TCOMAPI mReset(bool bExecute)=0;
};
_TCOM_SMARTPTR_TYPEDEF(ISoEProcess, IID_ISoEProcess);
#endif // !defined(_TC_TYPE_970DA61A_269B_41C3_8941_02F0458E1BF8_INCLUDED_)

#if !defined(_TC_TYPE_BAA6EC0B_E089_4261_B526_D49D4945A12E_INCLUDED_)
#define _TC_TYPE_BAA6EC0B_E089_4261_B526_D49D4945A12E_INCLUDED_
struct __declspec(novtable) IPanelProcess : public ITcUnknown
{
	virtual HRESULT TCOMAPI mInitialize()=0;
	virtual HRESULT TCOMAPI mFaultReset()=0;
	virtual HRESULT TCOMAPI mInput()=0;
	virtual HRESULT TCOMAPI mOutput()=0;
	virtual HRESULT TCOMAPI mHandwheelReset()=0;
};
_TCOM_SMARTPTR_TYPEDEF(IPanelProcess, IID_IPanelProcess);
#endif // !defined(_TC_TYPE_BAA6EC0B_E089_4261_B526_D49D4945A12E_INCLUDED_)

///</AutoGeneratedContent>
