///////////////////////////////////////////////////////////////////////////////
// MotionControlServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_MotionControl = 0x3F000000;
#define SRVNAME_MOTIONCONTROL "MotionControl"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_MotionControlCMotionControl = {0x73d79b9f,0xfc12,0x4c59,{0x97,0x3c,0x7e,0x93,0x7a,0x98,0x2d,0xda}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_MotionControlParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_54E74FBE_0A82_440E_8829_BF368D27C93C_INCLUDED_)
#define _TC_TYPE_54E74FBE_0A82_440E_8829_BF368D27C93C_INCLUDED_
typedef struct _MotionCommand
{
	double pos[5];
	double vel[5];
	double acc[5];
	double kp[5];
	double kv[5];
	double ka[5];
	SHORT opMode[5];
	unsigned char reserved1[2];
	ULONG commandIndex;
} MotionCommand, *PMotionCommand;
#endif // !defined(_TC_TYPE_54E74FBE_0A82_440E_8829_BF368D27C93C_INCLUDED_)

#if !defined(_TC_TYPE_F512F522_E8D1_4D42_8E2E_F11B4CC4AE58_INCLUDED_)
#define _TC_TYPE_F512F522_E8D1_4D42_8E2E_F11B4CC4AE58_INCLUDED_
typedef struct _MotionControlInfo
{
	SHORT AbsEncDir;
	unsigned char reserved1[2];
	LONG AbsEncRes;
	double RatedCurrent;
	double RatedTorque;
	SHORT TorDir;
	unsigned char reserved2[2];
	LONG AbsZeroPos;
	LONG PosUpperLimit;
	LONG PosLowerLimit;
	double TransmissionRatio;
	SHORT TorPdoMax;
	SHORT AdditiveTorque;
	bool AbsEncType;
	unsigned char reserved3;
	SHORT PositiveHardBit;
	SHORT NegativeHardBit;
	SHORT DriverType;
	bool Exposed;
	unsigned char reserved4[3];
} MotionControlInfo, *PMotionControlInfo;
#endif // !defined(_TC_TYPE_F512F522_E8D1_4D42_8E2E_F11B4CC4AE58_INCLUDED_)

#if !defined(_TC_TYPE_BC7271FA_55C3_4AA8_BB20_A421FAF1BB9F_INCLUDED_)
#define _TC_TYPE_BC7271FA_55C3_4AA8_BB20_A421FAF1BB9F_INCLUDED_
typedef struct _DriverInput
{
	USHORT StatusWord;
	unsigned char reserved1[2];
	LONG ActualAbsPos;
	SHORT ActualTor;
	unsigned char reserved2[2];
	LONG ActualVel;
	SHORT ErrorCode;
	SHORT WarningCode;
	SHORT DigitalInput_1;
	unsigned char reserved3[2];
} DriverInput, *PDriverInput;
#endif // !defined(_TC_TYPE_BC7271FA_55C3_4AA8_BB20_A421FAF1BB9F_INCLUDED_)

#if !defined(_TC_TYPE_B4A9A927_0308_4BB0_8808_D7AD02AF7FD9_INCLUDED_)
#define _TC_TYPE_B4A9A927_0308_4BB0_8808_D7AD02AF7FD9_INCLUDED_
typedef struct _DriverOutput
{
	USHORT ControlWord;
	unsigned char reserved1[2];
	LONG TargetPosition;
	SHORT TargetTorque;
	unsigned char reserved2[2];
	LONG TargetVelocity;
	char OperationMode;
	unsigned char reserved3[3];
} DriverOutput, *PDriverOutput;
#endif // !defined(_TC_TYPE_B4A9A927_0308_4BB0_8808_D7AD02AF7FD9_INCLUDED_)

#if !defined(_TC_TYPE_19F1CFB7_C2CD_4BF7_AA2D_C3C6265BA72D_INCLUDED_)
#define _TC_TYPE_19F1CFB7_C2CD_4BF7_AA2D_C3C6265BA72D_INCLUDED_
enum SystemState : SHORT {
	eIdle = 0,
	eInitialization = 1,
	eDisabled = 2,
	eStandby = 3,
	eMoving = 4,
	eHandwheel = 5,
	eLimitViolation = 6,
	eFault = 7,
	eEmergency = 8,
	eTest = 9
};
#endif // !defined(_TC_TYPE_19F1CFB7_C2CD_4BF7_AA2D_C3C6265BA72D_INCLUDED_)

#if !defined(_TC_TYPE_95413D15_9E1D_4CB4_ACF8_2935AB049785_INCLUDED_)
#define _TC_TYPE_95413D15_9E1D_4CB4_ACF8_2935AB049785_INCLUDED_
typedef struct _PanelInfo
{
	bool ServoOn;
	unsigned char reserved1;
	SHORT Handwheel_EnabledAxisNum;
	unsigned char reserved2[4];
	double Handwheel_Ratio;
	double Handwheel_dPos[5];
	SHORT Spindle_Cmd;
	bool Reset;
	unsigned char reserved3[5];
} PanelInfo, *PPanelInfo;
#endif // !defined(_TC_TYPE_95413D15_9E1D_4CB4_ACF8_2935AB049785_INCLUDED_)

#if !defined(_TC_TYPE_75816603_8B01_41ED_9F49_1001E13236B1_INCLUDED_)
#define _TC_TYPE_75816603_8B01_41ED_9F49_1001E13236B1_INCLUDED_
enum OpMode : SHORT {
	CSP = 8,
	CSV = 9,
	CST = 10
};
#endif // !defined(_TC_TYPE_75816603_8B01_41ED_9F49_1001E13236B1_INCLUDED_)

#if !defined(_TC_TYPE_760AEB87_AF7B_4178_B0AF_C2E7472652E4_INCLUDED_)
#define _TC_TYPE_760AEB87_AF7B_4178_B0AF_C2E7472652E4_INCLUDED_
enum DriverState : USHORT {
	eNotReadyForPowerUp = 0,
	eShutDownError = 40960,
	eLogicReadyForPowerOn = 16384,
	ePowerStageLocked = 32768,
	eReadyToOperate = 49152
};
#endif // !defined(_TC_TYPE_760AEB87_AF7B_4178_B0AF_C2E7472652E4_INCLUDED_)

#if !defined(_TC_TYPE_8A0CBD64_A622_4812_96E8_6466F6FAD96D_INCLUDED_)
#define _TC_TYPE_8A0CBD64_A622_4812_96E8_6466F6FAD96D_INCLUDED_
enum MasterControlWord : USHORT {
	eHaltDrive = 0,
	eStopDrive = 1,
	eControlUnitSync = 1024,
	eRestartDrive = 8192,
	eDriveOff = 24576,
	eDriveOn_CSP = 57344,
	eDriveOn_CST = 57600,
	eDriveOn_CSV = 57856
};
#endif // !defined(_TC_TYPE_8A0CBD64_A622_4812_96E8_6466F6FAD96D_INCLUDED_)

#if !defined(_TC_TYPE_4CC52115_110B_4A46_936A_8C0B97DF661E_INCLUDED_)
#define _TC_TYPE_4CC52115_110B_4A46_936A_8C0B97DF661E_INCLUDED_
enum AxisOrder : SHORT {
	Axis_X = 1,
	Axis_Y = 2,
	Axis_Z = 3,
	Axis_A = 4,
	Axis_C = 5
};
#endif // !defined(_TC_TYPE_4CC52115_110B_4A46_936A_8C0B97DF661E_INCLUDED_)

#if !defined(_TC_TYPE_5DD60AB0_71F1_498E_8938_F34CED0A4C68_INCLUDED_)
#define _TC_TYPE_5DD60AB0_71F1_498E_8938_F34CED0A4C68_INCLUDED_
typedef struct _AxisInformation
{
	double CurrentPos;
	double CurrentVel;
	SHORT CurrentTor;
	OpMode CurrentMode;
	unsigned char reserved1[4];
	double CommandPos;
	double CommandVel;
	SHORT CommandTor;
	unsigned char reserved2[6];
} AxisInformation, *PAxisInformation;
#endif // !defined(_TC_TYPE_5DD60AB0_71F1_498E_8938_F34CED0A4C68_INCLUDED_)

#if !defined(_TC_TYPE_8A554618_FB22_4EDD_9FCF_D053B7A70EC0_INCLUDED_)
#define _TC_TYPE_8A554618_FB22_4EDD_9FCF_D053B7A70EC0_INCLUDED_
typedef struct _InterpolationParameter
{
	double MaxVelocity;
	double MaxAcceleration;
	double MaxJerk;
	double CycleTime;
	double Tolerance;
} InterpolationParameter, *PInterpolationParameter;
#endif // !defined(_TC_TYPE_8A554618_FB22_4EDD_9FCF_D053B7A70EC0_INCLUDED_)

#if !defined(_TC_TYPE_4B5AC5BB_8B06_4426_BEF8_58D5594E8029_INCLUDED_)
#define _TC_TYPE_4B5AC5BB_8B06_4426_BEF8_58D5594E8029_INCLUDED_
enum ControlWord_General : SHORT {
	eDisableVoltage = 0,
	eQuickStop = 2,
	eShutdown = 6,
	eDisableOperation = 7,
	eSwitchOn = 7,
	eEnableOperation = 15,
	eFaultReset = 128
};
#endif // !defined(_TC_TYPE_4B5AC5BB_8B06_4426_BEF8_58D5594E8029_INCLUDED_)

#if !defined(_TC_TYPE_AAD5C3CD_D2D5_46FE_BD9C_DC9AF7934969_INCLUDED_)
#define _TC_TYPE_AAD5C3CD_D2D5_46FE_BD9C_DC9AF7934969_INCLUDED_
enum DriverState_General : SHORT {
	eNotReadyToSwitchOn = 0,
	eSwitchOnDisabled = 64,
	eReadyToSwitchOn = 33,
	eSwitchedOn = 35,
	eOperationEnabled = 39,
	eQuickStopActive = 7,
	eFaultReactionActive = 15,
	eDriverFault = 8,
	eQuickStopBit = 32
};
#endif // !defined(_TC_TYPE_AAD5C3CD_D2D5_46FE_BD9C_DC9AF7934969_INCLUDED_)

typedef struct _MotionControlParameter
{
	MotionControlInfo DriverParameter[10];
	MotionControlInfo SpindleDriverParam;
	InterpolationParameter AxisGroupInterpolationParam[10];
	InterpolationParameter SpindleInterpolationParam;
} MotionControlParameter, *PMotionControlParameter;

typedef struct _MotionControlInputs
{
	MotionCommand CommandData;
	DriverInput AxisInputs[10];
	PanelInfo PanelInformation;
	bool mockButton[10];
	unsigned char reserved1[6];
	double TestInputs[20];
	DriverInput SpindleInput;
} MotionControlInputs, *PMotionControlInputs;

typedef struct _MotionControlOutputs
{
	DriverOutput AxisOutputs[10];
	struct {
		SystemState CurrentState;
		bool StateFlag[10];
	} StateMachine;
	unsigned char reserved1[4];
	struct {
		AxisInformation AxisStatus[6];
		double GantryDeviation;
	} AxisInfo;
	DriverOutput SpindleOutput;
	unsigned char reserved2[4];
} MotionControlOutputs, *PMotionControlOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_MotionControlInputs 0
#define ADI_MotionControlOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
