///////////////////////////////////////////////////////////////////////////////
// MotionControlClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "MotionControlClassFactory.h"
#include "MotionControlServices.h"
#include "MotionControlVersion.h"
#include "MotionControl.h"
#include "ModuleSpindle.h"
#include "ModuleSafety.h"
#include "ModuleAxisGroup.h"
#include "ModuleTool.h"

BEGIN_CLASS_MAP(CMotionControlClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_MotionControlCMotionControl, SRVNAME_MOTIONCONTROL "!CMotionControl", CMotionControl)
	CLASS_ENTRY(CID_MotionControlCModuleSpindle, SRVNAME_MOTIONCONTROL "!CModuleSpindle", CModuleSpindle)
	CLASS_ENTRY(CID_MotionControlCModuleSafety, SRVNAME_MOTIONCONTROL "!CModuleSafety", CModuleSafety)
	CLASS_ENTRY(CID_MotionControlCModuleAxisGroup, SRVNAME_MOTIONCONTROL "!CModuleAxisGroup", CModuleAxisGroup)
	CLASS_ENTRY(CID_MotionControlCModuleTool, SRVNAME_MOTIONCONTROL "!CModuleTool", CModuleTool)
///</AutoGeneratedContent>
END_CLASS_MAP()

CMotionControlClassFactory::CMotionControlClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_MOTIONCONTROL));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(MotionControl));
#endif //defined(TCDBG_UNIT_VERSION)
}

