///////////////////////////////////////////////////////////////////////////////
// MotorControlServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_MotorControl = 0x3F000000;
#define SRVNAME_MOTORCONTROL "MotorControl"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_MotorControlCMotorControl = {0x478c6498,0x483d,0x408c,{0x90,0xdd,0x5b,0x07,0xc4,0x65,0x84,0x35}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_MotorControlParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_FD9A51F2_D290_4265_856B_B0A2E6461283_INCLUDED_)
#define _TC_TYPE_FD9A51F2_D290_4265_856B_B0A2E6461283_INCLUDED_
typedef struct _MotionCommand
{
	double pos[5];
	double vel[5];
	double acc[5];
	double kp[5];
	double kv[5];
	double ka[5];
	SHORT opMode[5];
	unsigned char reserved1[2];
	ULONG commandIndex;
} MotionCommand, *PMotionCommand;
#endif // !defined(_TC_TYPE_FD9A51F2_D290_4265_856B_B0A2E6461283_INCLUDED_)

typedef struct _MotorControlParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} MotorControlParameter, *PMotorControlParameter;

typedef struct _MotorControlInputs
{
	MotionCommand CommandData;
} MotorControlInputs, *PMotorControlInputs;

#pragma pack(push,1)
typedef struct _MotorControlOutputs
{
} MotorControlOutputs, *PMotorControlOutputs;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_MotorControlInputs 0
#define ADI_MotorControlOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
