///////////////////////////////////////////////////////////////////////////////
// MotorControlClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "MotorControlClassFactory.h"
#include "MotorControlServices.h"
#include "MotorControlVersion.h"
#include "MotorControl.h"

BEGIN_CLASS_MAP(CMotorControlClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_MotorControlCMotorControl, SRVNAME_MOTORCONTROL "!CMotorControl", CMotorControl)
///</AutoGeneratedContent>
END_CLASS_MAP()

CMotorControlClassFactory::CMotorControlClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_MOTORCONTROL));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(MotorControl));
#endif //defined(TCDBG_UNIT_VERSION)
}

