///////////////////////////////////////////////////////////////////////////////
// ruckigInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "ruckigServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
