///////////////////////////////////////////////////////////////////////////////
// ruckigServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_ruckig = 0x3F000000;
#define SRVNAME_RUCKIG "ruckig"

///<AutoGeneratedContent id="ClassIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
///</AutoGeneratedContent>


