///////////////////////////////////////////////////////////////////////////////
// ModuleTestServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_ModuleTest = 0x3F000000;
#define SRVNAME_MODULETEST "ModuleTest"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ModuleTestCModuleTest = {0xf02a5a57,0xd261,0x4db6,{0xa0,0x6d,0xa7,0xfb,0xbc,0x0b,0x58,0x25}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ModuleTestParameter = 0x00000001;
const PTCID PID_ModuleTestTestAxisGroup_Interface = 0x00000002;
const PTCID PID_ModuleTestTestSpindle_Interface = 0x00000003;
const PTCID PID_ModuleTestTestSafety_Interface = 0x00000004;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_13C5ED93_554D_47D2_9A08_D46CC349EDDD_INCLUDED_)
#define _TC_TYPE_13C5ED93_554D_47D2_9A08_D46CC349EDDD_INCLUDED_
typedef struct _PanelInfo
{
	bool ServoOn;
	unsigned char reserved1;
	SHORT Handwheel_EnabledAxisNum;
	unsigned char reserved2[4];
	double Handwheel_Ratio;
	double Handwheel_dPos[5];
	SHORT Spindle_Cmd;
	bool Reset;
	bool Execute;
	unsigned char reserved3[4];
} PanelInfo, *PPanelInfo;
#endif // !defined(_TC_TYPE_13C5ED93_554D_47D2_9A08_D46CC349EDDD_INCLUDED_)

#if !defined(_TC_TYPE_9C29111D_2AB9_43BB_ACE9_11CADBF59920_INCLUDED_)
#define _TC_TYPE_9C29111D_2AB9_43BB_ACE9_11CADBF59920_INCLUDED_
typedef struct _SpindleRot
{
	double TargetVel;
} SpindleRot, *PSpindleRot;
#endif // !defined(_TC_TYPE_9C29111D_2AB9_43BB_ACE9_11CADBF59920_INCLUDED_)

#if !defined(_TC_TYPE_9689CD0C_E531_4687_BB83_6D4BB1F2F1CD_INCLUDED_)
#define _TC_TYPE_9689CD0C_E531_4687_BB83_6D4BB1F2F1CD_INCLUDED_
typedef struct _SpindleVelLimit
{
	double MaxVel;
	double MaxAcc;
	double MaxJerk;
} SpindleVelLimit, *PSpindleVelLimit;
#endif // !defined(_TC_TYPE_9689CD0C_E531_4687_BB83_6D4BB1F2F1CD_INCLUDED_)

#if !defined(_TC_TYPE_BEAC0974_F61C_4504_BEF4_0C5C6361CD2E_INCLUDED_)
#define _TC_TYPE_BEAC0974_F61C_4504_BEF4_0C5C6361CD2E_INCLUDED_
typedef struct _SpindlePosition
{
	double TargetPos;
	double TargetVel;
} SpindlePosition, *PSpindlePosition;
#endif // !defined(_TC_TYPE_BEAC0974_F61C_4504_BEF4_0C5C6361CD2E_INCLUDED_)

#if !defined(_TC_TYPE_DF678954_0CC7_4B57_A830_AD3AD6D5FFCE_INCLUDED_)
#define _TC_TYPE_DF678954_0CC7_4B57_A830_AD3AD6D5FFCE_INCLUDED_
enum SpindleState : SHORT {
	eSpindleIdle = 0,
	eSpindleInitialization = 1,
	eSpindleDisabled = 2,
	eSpindleEnable = 3,
	eSpindlePreMoving = 4,
	eSpindleRotating = 5,
	eSpindlePositioning = 6,
	eSpindlePostMoving = 7,
	eSpindleEmergency = 8,
	eSpindleFault = 9,
	eSpindleTest = 10
};
#endif // !defined(_TC_TYPE_DF678954_0CC7_4B57_A830_AD3AD6D5FFCE_INCLUDED_)

#if !defined(_TC_TYPE_75816603_8B01_41ED_9F49_1001E13236B1_INCLUDED_)
#define _TC_TYPE_75816603_8B01_41ED_9F49_1001E13236B1_INCLUDED_
enum OpMode : SHORT {
	CSP = 8,
	CSV = 9,
	CST = 10
};
#endif // !defined(_TC_TYPE_75816603_8B01_41ED_9F49_1001E13236B1_INCLUDED_)

#if !defined(_TC_TYPE_6C52FF3C_3F1E_4DF4_B88E_56EAE4037B12_INCLUDED_)
#define _TC_TYPE_6C52FF3C_3F1E_4DF4_B88E_56EAE4037B12_INCLUDED_
typedef struct _MetaData
{
	unsigned char CommandType;
	unsigned char reserved1[3];
	ULONG SourceActionBlockIndex;
	ULONG Index;
} MetaData, *PMetaData;
#endif // !defined(_TC_TYPE_6C52FF3C_3F1E_4DF4_B88E_56EAE4037B12_INCLUDED_)

#if !defined(_TC_TYPE_0C8C736F_2009_4A9B_BA79_A373A15B7252_INCLUDED_)
#define _TC_TYPE_0C8C736F_2009_4A9B_BA79_A373A15B7252_INCLUDED_
typedef struct _OtherCommand
{
	ULONG CommandFunction;
	unsigned char reserved1[4];
	double Data;
} OtherCommand, *POtherCommand;
#endif // !defined(_TC_TYPE_0C8C736F_2009_4A9B_BA79_A373A15B7252_INCLUDED_)

#if !defined(_TC_TYPE_5CBC67ED_7FEB_485B_91B9_3CE3460A4A42_INCLUDED_)
#define _TC_TYPE_5CBC67ED_7FEB_485B_91B9_3CE3460A4A42_INCLUDED_
typedef struct _AxisInformation
{
	double CurrentPos;
	double CurrentVel;
	SHORT CurrentTor;
	unsigned char CurrentMode;
	unsigned char reserved1[5];
	double CommandPos;
	double CommandVel;
	SHORT CommandTor;
	SHORT CurrentStatus;
	unsigned char reserved2[4];
} AxisInformation, *PAxisInformation;
#endif // !defined(_TC_TYPE_5CBC67ED_7FEB_485B_91B9_3CE3460A4A42_INCLUDED_)

#if !defined(_TC_TYPE_85615354_18AB_4F2D_A42C_B832F67F7D5F_INCLUDED_)
#define _TC_TYPE_85615354_18AB_4F2D_A42C_B832F67F7D5F_INCLUDED_
typedef struct _AxisGroupInformation
{
	AxisInformation SingleAxisInformation[6];
	double GantryDeviation;
} AxisGroupInformation, *PAxisGroupInformation;
#endif // !defined(_TC_TYPE_85615354_18AB_4F2D_A42C_B832F67F7D5F_INCLUDED_)

#if !defined(_TC_TYPE_0BC67B36_C75E_4029_B338_FFB631C93168_INCLUDED_)
#define _TC_TYPE_0BC67B36_C75E_4029_B338_FFB631C93168_INCLUDED_
enum AxisGroupState : SHORT {
	eAxisGroupIdle = 0,
	eAxisGroupInitialization = 1,
	eAxisGroupDisabled = 2,
	eAxisGroupPreStandby = 3,
	eAxisGroupStandby = 4,
	eAxisGroupManualMoving = 5,
	eAxisGroupPreContinuousMoving = 6,
	eAxisGroupContinuousMoving = 7,
	eAxisGroupLimitViolation = 8,
	eAxisGroupEmergency = 9,
	eAxisGroupFault = 10,
	eAxisGroupRecovery = 11,
	eAxisGroupTest = 12,
	eAxisGroupPositioning = 13
};
#endif // !defined(_TC_TYPE_0BC67B36_C75E_4029_B338_FFB631C93168_INCLUDED_)

#if !defined(_TC_TYPE_2AB905D5_7D46_411F_BE58_01268BBF5FBB_INCLUDED_)
#define _TC_TYPE_2AB905D5_7D46_411F_BE58_01268BBF5FBB_INCLUDED_
enum AxisOrder : SHORT {
	Axis_X = 1,
	Axis_Y = 2,
	Axis_Z = 3,
	Axis_A = 4,
	Axis_C = 5,
	Spindle = 6
};
#endif // !defined(_TC_TYPE_2AB905D5_7D46_411F_BE58_01268BBF5FBB_INCLUDED_)

#if !defined(_TC_TYPE_B12E5C91_9B4E_4C5F_8515_574B83ACC3F6_INCLUDED_)
#define _TC_TYPE_B12E5C91_9B4E_4C5F_8515_574B83ACC3F6_INCLUDED_
typedef struct _NewMotionCommand
{
	double Pos[5];
	double Vel[5];
	double Acc[5];
	double AdditivePos[5];
	double AdditiveVel[5];
	double AdditiveTor[5];
} NewMotionCommand, *PNewMotionCommand;
#endif // !defined(_TC_TYPE_B12E5C91_9B4E_4C5F_8515_574B83ACC3F6_INCLUDED_)

#if !defined(_TC_TYPE_B1C3DEDA_F44B_40B0_BA64_EAB208DE948D_INCLUDED_)
#define _TC_TYPE_B1C3DEDA_F44B_40B0_BA64_EAB208DE948D_INCLUDED_
typedef struct _FullCommand
{
	MetaData metaData;
	unsigned char reserved1[4];
	NewMotionCommand motionCommand;
	OtherCommand otherCommand;
} FullCommand, *PFullCommand;
#endif // !defined(_TC_TYPE_B1C3DEDA_F44B_40B0_BA64_EAB208DE948D_INCLUDED_)

typedef struct _ModuleTestParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} ModuleTestParameter, *PModuleTestParameter;

typedef struct _ModuleTestInputs
{
	PanelInfo MockPanel;
	bool RecoveryButton;
	bool ContinuousButton;
	unsigned char reserved1[6];
	AxisGroupInformation TestAxisGroupInfo;
	bool GetParamKpButton;
	bool GetParamKvButton;
	bool GetParamTnButton;
	bool SetParamKpButton;
	bool SetParamKvButton;
	bool SetParamTnButton;
	bool PositionY;
	bool PositionX;
	bool PositionZ;
	unsigned char reserved2[7];
} ModuleTestInputs, *PModuleTestInputs;

typedef struct _ModuleTestOutputs
{
	struct {
		SHORT SelectedAxis;
		unsigned char reserved1[6];
		double MockCommandPos[5];
	} MockManualMovingCommand;
	FullCommand MockContinuousMovingCommand;
	double TestOutputs[10];
	unsigned char reserved1[48];
} ModuleTestOutputs, *PModuleTestOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_ModuleTestInputs 0
#define ADI_ModuleTestOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_A5B190D2_781F_49A4_9D2B_66AD8519040D_INCLUDED_)
#define _TC_IID_A5B190D2_781F_49A4_9D2B_66AD8519040D_INCLUDED_
TCOM_DECL_INTERFACE("a5b190d2-781f-49a4-9d2b-66ad8519040d", ISpindleInterface)
#endif // !defined(_TC_IID_A5B190D2_781F_49A4_9D2B_66AD8519040D_INCLUDED_)

#if !defined(_TC_IID_125C4828_6162_4C51_984A_E44EFC60C49E_INCLUDED_)
#define _TC_IID_125C4828_6162_4C51_984A_E44EFC60C49E_INCLUDED_
TCOM_DECL_INTERFACE("125c4828-6162-4c51-984a-e44efc60c49e", IAxisGroupInterface)
#endif // !defined(_TC_IID_125C4828_6162_4C51_984A_E44EFC60C49E_INCLUDED_)

#if !defined(_TC_IID_DFA7B551_502B_4085_88E7_A88921AF739F_INCLUDED_)
#define _TC_IID_DFA7B551_502B_4085_88E7_A88921AF739F_INCLUDED_
TCOM_DECL_INTERFACE("dfa7b551-502b-4085-88e7-a88921af739f", ISafetyInterface)
#endif // !defined(_TC_IID_DFA7B551_502B_4085_88E7_A88921AF739F_INCLUDED_)

#if !defined(_TC_IID_125C4828_6162_4C51_984A_E44EFC60C49E_INCLUDED_)
#define _TC_IID_125C4828_6162_4C51_984A_E44EFC60C49E_INCLUDED_
TCOM_DECL_INTERFACE("125c4828-6162-4c51-984a-e44efc60c49e", IAxisGroupInterface)
#endif // !defined(_TC_IID_125C4828_6162_4C51_984A_E44EFC60C49E_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
