///////////////////////////////////////////////////////////////////////////////
// ModuleTestInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "ModuleTestServices.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_A5B190D2_781F_49A4_9D2B_66AD8519040D_INCLUDED_)
#define _TC_TYPE_A5B190D2_781F_49A4_9D2B_66AD8519040D_INCLUDED_
struct __declspec(novtable) ISpindleInterface : public ITcUnknown
{
	virtual HRESULT TCOMAPI RequestRotating(SpindleRot RotData)=0;
	virtual HRESULT TCOMAPI RequestStop()=0;
	virtual HRESULT TCOMAPI SetVelLimit(SpindleVelLimit VelLimit)=0;
	virtual HRESULT TCOMAPI RequestPositioning(SpindlePosition PositionData)=0;
	virtual HRESULT TCOMAPI ReportCurrentState(SpindleState& curr_state)=0;
	virtual HRESULT TCOMAPI RequestSpindleEnable()=0;
	virtual HRESULT TCOMAPI IsSpindleEnable(bool& is_enable)=0;
	virtual HRESULT TCOMAPI IsSpindleMoving(bool& is_moving)=0;
	virtual HRESULT TCOMAPI RequestFault()=0;
	virtual HRESULT TCOMAPI RequestReset()=0;
	virtual HRESULT TCOMAPI RequestSpindleDisable()=0;
};
_TCOM_SMARTPTR_TYPEDEF(ISpindleInterface, IID_ISpindleInterface);
#endif // !defined(_TC_TYPE_A5B190D2_781F_49A4_9D2B_66AD8519040D_INCLUDED_)

#if !defined(_TC_TYPE_92B58E62_00D3_492F_A964_14316BC3B3CF_INCLUDED_)
#define _TC_TYPE_92B58E62_00D3_492F_A964_14316BC3B3CF_INCLUDED_
struct __declspec(novtable) IAxisGroupInterface : public ITcUnknown
{
	virtual HRESULT TCOMAPI ReportCurrentState(AxisGroupState& curr_state)=0;
	virtual HRESULT TCOMAPI RequestEnterHandwheel()=0;
	virtual HRESULT TCOMAPI RequestQuitHandwheel()=0;
	virtual HRESULT TCOMAPI RequestContinuousMoving()=0;
	virtual HRESULT TCOMAPI RequestStop()=0;
	virtual HRESULT TCOMAPI RequestAxisGroupEnable()=0;
	virtual HRESULT TCOMAPI RequestAxisGroupDisable()=0;
	virtual HRESULT TCOMAPI RequestReset()=0;
	virtual HRESULT TCOMAPI RequestChangeOpMode(OpMode mode)=0;
	virtual HRESULT TCOMAPI IsAxisGroupStandby(bool& is_standby)=0;
	virtual HRESULT TCOMAPI IsAxisGroupMoving(bool& is_moving)=0;
	virtual HRESULT TCOMAPI IsAxisGroupOpModeSwitched(bool& is_switched)=0;
	virtual HRESULT TCOMAPI IsAxisGroupDisabled(bool& is_disabled)=0;
	virtual HRESULT TCOMAPI IsAxisGroupManualMoving(bool& is_manual)=0;
	virtual HRESULT TCOMAPI RequestFault()=0;
};
_TCOM_SMARTPTR_TYPEDEF(IAxisGroupInterface, IID_IAxisGroupInterface);
#endif // !defined(_TC_TYPE_92B58E62_00D3_492F_A964_14316BC3B3CF_INCLUDED_)

#if !defined(_TC_TYPE_DFA7B551_502B_4085_88E7_A88921AF739F_INCLUDED_)
#define _TC_TYPE_DFA7B551_502B_4085_88E7_A88921AF739F_INCLUDED_
struct __declspec(novtable) ISafetyInterface : public ITcUnknown
{
	virtual HRESULT TCOMAPI EnterRecoveryState()=0;
	virtual HRESULT TCOMAPI LeaveRecoveryState()=0;
};
_TCOM_SMARTPTR_TYPEDEF(ISafetyInterface, IID_ISafetyInterface);
#endif // !defined(_TC_TYPE_DFA7B551_502B_4085_88E7_A88921AF739F_INCLUDED_)

///</AutoGeneratedContent>
