///////////////////////////////////////////////////////////////////////////////
// ModuleTestClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "ModuleTestClassFactory.h"
#include "ModuleTestServices.h"
#include "ModuleTestVersion.h"
#include "ModuleTest.h"

BEGIN_CLASS_MAP(CModuleTestClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_ModuleTestCModuleTest, SRVNAME_MODULETEST "!CModuleTest", CModuleTest)
///</AutoGeneratedContent>
END_CLASS_MAP()

CModuleTestClassFactory::CModuleTestClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_MODULETEST));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(ModuleTest));
#endif //defined(TCDBG_UNIT_VERSION)
}

