///////////////////////////////////////////////////////////////////////////////
// ModuleTestInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "ModuleTestServices.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_CF8E28DE_CFD4_4727_86E6_C55D5891DD9F_INCLUDED_)
#define _TC_TYPE_CF8E28DE_CFD4_4727_86E6_C55D5891DD9F_INCLUDED_
struct __declspec(novtable) ISpindleInterface : public ITcUnknown
{
	virtual HRESULT TCOMAPI RequestRotating(SpindleRot RotData)=0;
	virtual HRESULT TCOMAPI RequestStop()=0;
	virtual HRESULT TCOMAPI SetVelLimit(SpindleVelLimit VelLimit)=0;
	virtual HRESULT TCOMAPI RequestPositioning(SpindlePosition PositionData)=0;
	virtual HRESULT TCOMAPI ReportCurrentState(SpindleState& curr_state)=0;
	virtual HRESULT TCOMAPI RequestSpindleEnable()=0;
	virtual HRESULT TCOMAPI IsSpindleEnable(bool& is_enable)=0;
	virtual HRESULT TCOMAPI IsSpindleMoving(bool& is_moving)=0;
};
_TCOM_SMARTPTR_TYPEDEF(ISpindleInterface, IID_ISpindleInterface);
#endif // !defined(_TC_TYPE_CF8E28DE_CFD4_4727_86E6_C55D5891DD9F_INCLUDED_)

#if !defined(_TC_TYPE_08CC0D90_8987_4A20_A338_22772737A054_INCLUDED_)
#define _TC_TYPE_08CC0D90_8987_4A20_A338_22772737A054_INCLUDED_
struct __declspec(novtable) IAxisGroupInterface : public ITcUnknown
{
	virtual HRESULT TCOMAPI ReportCurrentState(AxisGroupState& curr_state)=0;
	virtual HRESULT TCOMAPI RequestEnterHandwheel()=0;
	virtual HRESULT TCOMAPI RequestQuitHandwheel()=0;
	virtual HRESULT TCOMAPI RequestContinuousMoving()=0;
	virtual HRESULT TCOMAPI RequestStop()=0;
	virtual HRESULT TCOMAPI RequestAxisGroupEnable()=0;
	virtual HRESULT TCOMAPI RequestAxisGroupDisable()=0;
	virtual HRESULT TCOMAPI RequestReset()=0;
	virtual HRESULT TCOMAPI RequestRecovery(bool is_entered)=0;
	virtual HRESULT TCOMAPI RequestChangeOpMode(OpMode mode)=0;
	virtual HRESULT TCOMAPI IsAxisGroupStandby(bool& is_standby)=0;
	virtual HRESULT TCOMAPI IsAxisGroupMoving(bool& is_moving)=0;
	virtual HRESULT TCOMAPI IsAxisGroupOpModeSwitched(bool& is_switched)=0;
	virtual HRESULT TCOMAPI IsAxisGroupDisabled(bool& is_disabled)=0;
	virtual HRESULT TCOMAPI IsAxisGroupManualMoving(bool& is_manual)=0;
};
_TCOM_SMARTPTR_TYPEDEF(IAxisGroupInterface, IID_IAxisGroupInterface);
#endif // !defined(_TC_TYPE_08CC0D90_8987_4A20_A338_22772737A054_INCLUDED_)

///</AutoGeneratedContent>
