///////////////////////////////////////////////////////////////////////////////
// ModuleTest.h
#pragma once

#include "ModuleTestInterfaces.h"
#include "TestController.h"

class CModuleTest 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_ModuleTestCModuleTest)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CModuleTest();
	virtual	~CModuleTest();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	// Other module RPC
	bool m_IsRpcReady = false;
	bool InitializeOtherModuleRpc();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	ModuleTestParameter m_Parameter;
	ModuleTestInputs m_Inputs;
	ModuleTestOutputs m_Outputs;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
	IAxisGroupInterfacePtr m_spTestAxisGroup_Interface;
	ISpindleInterfacePtr m_spTestSpindle_Interface;
	ISafetyInterfacePtr m_spTestSafety_Interface;
///</AutoGeneratedContent>

	CTestController m_TestController;
};
