///////////////////////////////////////////////////////////////////////////////
// ModuleSimulationClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "ModuleSimulationClassFactory.h"
#include "ModuleSimulationServices.h"
#include "ModuleSimulationVersion.h"
#include "ModuleSimulation.h"

BEGIN_CLASS_MAP(CModuleSimulationClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_ModuleSimulationCModuleSimulation, SRVNAME_MODULESIMULATION "!CModuleSimulation", CModuleSimulation)
///</AutoGeneratedContent>
END_CLASS_MAP()

CModuleSimulationClassFactory::CModuleSimulationClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_MODULESIMULATION));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(ModuleSimulation));
#endif //defined(TCDBG_UNIT_VERSION)
}

