///////////////////////////////////////////////////////////////////////////////
// ModuleSimulation.cpp
#include "TcPch.h"
#pragma hdrstop

#include "ModuleSimulation.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// CModuleSimulation
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CModuleSimulation
BEGIN_INTERFACE_MAP(CModuleSimulation)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
///</AutoGeneratedContent>
END_INTERFACE_MAP()


IMPLEMENT_ITCOMOBJECT(CModuleSimulation)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CModuleSimulation)
IMPLEMENT_ITCADI(CModuleSimulation)
IMPLEMENT_ITCWATCHSOURCE(CModuleSimulation)


///////////////////////////////////////////////////////////////////////////////
// Set parameters of CModuleSimulation 
BEGIN_SETOBJPARA_MAP(CModuleSimulation)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_ModuleSimulationParameter, m_Parameter)
	SETOBJPARA_VALUE(PID_Ctx_TaskCycleNs, m_TaskCycleTime)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CModuleSimulation 
BEGIN_GETOBJPARA_MAP(CModuleSimulation)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_ModuleSimulationParameter, m_Parameter)
	GETOBJPARA_VALUE(PID_Ctx_TaskCycleNs, m_TaskCycleTime)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CModuleSimulation
BEGIN_OBJPARAWATCH_MAP(CModuleSimulation)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CModuleSimulation
BEGIN_OBJDATAAREA_MAP(CModuleSimulation)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(ADI_ModuleSimulationInputs, m_Inputs)
	OBJDATAAREA_VALUE(ADI_ModuleSimulationOutputs, m_Outputs)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
CModuleSimulation::CModuleSimulation()
	: m_Trace(m_TraceLevelMax, m_spSrv)
{
///<AutoGeneratedContent id="MemberInitialization">
	m_TraceLevelMax = tlAlways;
	memset(&m_Parameter, 0, sizeof(m_Parameter));
	m_TaskCycleTime = 0;
	memset(&m_Inputs, 0, sizeof(m_Inputs));
	memset(&m_Outputs, 0, sizeof(m_Outputs));
///</AutoGeneratedContent>
}

///////////////////////////////////////////////////////////////////////////////
CModuleSimulation::~CModuleSimulation() 
{
}


///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CModuleSimulation)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CModuleSimulation::SetObjStatePS(PTComInitDataHdr pInitData)
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	hr = m_spSrv->TcCreateInstance(CID_TcFileAccess, IID_ITcFileAccess, (PPVOID)(&m_spFileAccess));
	m_Trace.Log(tlAlways, "TcCreateInstance Created - hr=0x%08x", hr);

	char xml_file_axis_group[kMaxRead];
	char xml_file_spindle[kMaxRead] ;

	if (SUCCEEDED(hr)) {
		m_Trace.Log(tlAlways, FNAMEA "Changing state of TcFileAccess");
		ITComObjectPtr spFileAccessObj = m_spFileAccess;
		hr = spFileAccessObj->TcSetObjState(TCOM_STATE_PREOP, m_spSrv, pInitData);
		m_Trace.Log(tlAlways, FNAMEA "TcFileAccess state changed - hr=0x%08x", hr);

		UINT n_reads_axis_group = ReadFile(m_AxisGroupConfigPath, xml_file_axis_group, kMaxRead - 1);
		xml_file_axis_group[n_reads_axis_group] = '\0';
		if (n_reads_axis_group >= kMaxRead - 1) {
			m_Trace.Log(tlError, "The configuration file has larger size than the preconfigured one %d!", kMaxRead);
			return S_FALSE;
		}

		UINT n_reads_spindle = ReadFile(m_SpindleConfigPath, xml_file_spindle, kMaxRead - 1);
		xml_file_spindle[n_reads_spindle] = '\0';
		if (n_reads_spindle >= kMaxRead - 1) {
			m_Trace.Log(tlError, "The configuration file has larger size than the preconfigured one %d!", kMaxRead);
			return S_FALSE;
		}
	}
	hr = ParseFileAndAssignValue(xml_file_axis_group, xml_file_spindle);

	if (hr == S_OK)
	{
		m_SimulationController.MapParameters(&m_Outputs, &m_Inputs, &m_Parameter);
		m_SimulationController.Initialize();
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CModuleSimulation::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	// TODO: Add any additional initialization


	// If following call is successful the CycleUpdate method will be called, 
	// possibly even before method has been left.
	hr = FAILED(hr) ? hr : AddModuleToCaller(); 

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		RemoveModuleFromCaller(); 
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CModuleSimulation::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;

	RemoveModuleFromCaller(); 

	// TODO: Add any additional deinitialization

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CModuleSimulation::SetObjStateSP()
{
	HRESULT hr = S_OK;
	m_Trace.Log(tlVerbose, FENTERA);

	if (m_spFileAccess != NULL)
	{
		ITComObjectPtr spFileAccessObj = m_spFileAccess;
		spFileAccessObj->TcSetObjState(TCOM_STATE_INIT, m_spSrv, NULL);
		spFileAccessObj = NULL;
		m_spFileAccess = NULL;
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CModuleSimulation::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;

	m_SimulationController.Run();

	return hr;
}
///</AutoGeneratedContent>

///////////////////////////////////////////////////////////////////////////////
HRESULT CModuleSimulation::AddModuleToCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;
	if ( m_spCyclicCaller.HasOID() )
	{
		if ( SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)) )
		{
			if ( FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))) )
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID; 
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CModuleSimulation::RemoveModuleFromCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);

	if ( m_spCyclicCaller )
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller	= NULL;

	m_Trace.Log(tlVerbose, FLEAVEA);
}

///////////////////////////////////////////////////////////////////////////////
UINT CModuleSimulation::ReadFile(PCCH szFileNameRead, char* contents, UINT max_read)
{
	HRESULT hr = S_OK;
	m_Trace.Log(tlAlways, FENTERA "szFileNameRead=%s", szFileNameRead);

	UINT nRead = 0;
	if (contents)
	{
		TcFileHandle hFile = NULL;
		hr = m_spFileAccess->FileOpen(szFileNameRead, static_cast<TcFileAccessMode>(amBinary | amRead), &hFile);
		m_Trace.Log(tlVerbose, "FileOpen hFile ");
		if (SUCCEEDED(hr))
		{
			m_Trace.Log(tlVerbose, "FileRead hFile ");
			m_spFileAccess->FileRead(hFile, contents, max_read, &nRead);
			m_spFileAccess->FileClose(hFile);
		}
	}
	m_Trace.Log(tlAlways, FLEAVEA "total bytes read=%d", nRead);
	return nRead;
}

///////////////////////////////////////////////////////////////////////////////
HRESULT CModuleSimulation::ParseFileAndAssignValue(const char* xml_axis_group, const char* xml_spindle)
{
	HRESULT hr = S_OK;

	XMLDocument doc_AxisGroup;

	// Parse AxisGroup.xml
	doc_AxisGroup.Parse(xml_axis_group);

	XMLElement* p_root_element = doc_AxisGroup.FirstChildElement("AxisGroup");
	XMLElement* p_axes = p_root_element->FirstChildElement("axes");

	int total_driver_num = 0;

	while (p_axes) {
		XMLElement* p_axis = p_axes->FirstChildElement("axis");

		int driver_num = 0;
		while (p_axis) {
			XMLElement* ptr = p_axis->FirstChildElement("AbsEncoderDir");
			m_Parameter.AxisGroupParam[total_driver_num].AbsEncDir = atoi(ptr->GetText());

			ptr = p_axis->FirstChildElement("AbsEncoderRes");
			m_Parameter.AxisGroupParam[total_driver_num].AbsEncRes = atol(ptr->GetText());

			ptr = p_axis->FirstChildElement("RatedCurr");
			m_Parameter.AxisGroupParam[total_driver_num].RatedCurrent = atof(ptr->GetText());

			ptr = p_axis->FirstChildElement("RatedTor");
			m_Parameter.AxisGroupParam[total_driver_num].RatedTorque = atof(ptr->GetText());

			ptr = p_axis->FirstChildElement("TorDir");
			m_Parameter.AxisGroupParam[total_driver_num].TorDir = atoi(ptr->GetText());

			ptr = p_axis->FirstChildElement("AbsZeroPos");
			m_Parameter.AxisGroupParam[total_driver_num].AbsZeroPos = atol(ptr->GetText());

			ptr = p_axis->FirstChildElement("TransmissionRatio");
			m_Parameter.AxisGroupParam[total_driver_num].TransmissionRatio = atof(ptr->GetText());

			ptr = p_axis->FirstChildElement("TorPdoMax");
			m_Parameter.AxisGroupParam[total_driver_num].TorPdoMax = atoi(ptr->GetText());

			ptr = p_axis->FirstChildElement("AdditiveTor");
			m_Parameter.AxisGroupParam[total_driver_num].AdditiveTorque = atoi(ptr->GetText());

			ptr = p_axis->FirstChildElement("MoveType");
			m_Parameter.AxisGroupParam[total_driver_num].MoveType = atoi(ptr->GetText());

			ptr = p_axis->FirstChildElement("DriverType");
			m_Parameter.AxisGroupParam[total_driver_num].DriverType = atoi(ptr->GetText());

			ptr = p_axis->FirstChildElement("Exposed");
			m_Parameter.AxisGroupParam[total_driver_num].Exposed = bool(atoi(ptr->GetText()));

			ptr = p_axis->FirstChildElement("MaxVelocity");
			ptr = p_axis->FirstChildElement("MaxAcceleration");
			ptr = p_axis->FirstChildElement("MaxJerk");
			
			total_driver_num++;
			p_axis = p_axis->NextSiblingElement("axis");
		}
		p_axes = p_axes->NextSiblingElement("axes");
	}
	m_Parameter.ActualAxisGroupDriverNum = total_driver_num;

	// Confirm all parameters have been loaded
	if (m_Parameter.AxisGroupParam[total_driver_num - 1].TorPdoMax < kEpsilon)
	{
		return S_FALSE;

		m_Parameter.ActualAxisGroupDriverNum = 0;
	}

	XMLDocument doc_Spindle;

	// Parse Spindle.xml
	doc_Spindle.Parse(xml_spindle);

	XMLElement* p_root_element_spindle = doc_Spindle.FirstChildElement("Spindle");
	XMLElement* p_axes_spindle = p_root_element_spindle->FirstChildElement("axes");

	while (p_axes_spindle) {
		XMLElement* p_axis_spindle = p_axes_spindle->FirstChildElement("axis");

		int driver_num = 0;
		while (p_axis_spindle) {
			XMLElement* ptr_spindle = p_axis_spindle->FirstChildElement("AbsEncoderDir");
			m_Parameter.SpindleParam.AbsEncDir = atoi(ptr_spindle->GetText());

			ptr_spindle = p_axis_spindle->FirstChildElement("AbsEncoderRes");
			m_Parameter.SpindleParam.AbsEncRes = atol(ptr_spindle->GetText());

			ptr_spindle = p_axis_spindle->FirstChildElement("RatedCurr");
			m_Parameter.SpindleParam.RatedCurrent = atof(ptr_spindle->GetText());

			ptr_spindle = p_axis_spindle->FirstChildElement("RatedTor");
			m_Parameter.SpindleParam.RatedTorque = atof(ptr_spindle->GetText());

			ptr_spindle = p_axis_spindle->FirstChildElement("TorDir");
			m_Parameter.SpindleParam.TorDir = atoi(ptr_spindle->GetText());

			ptr_spindle = p_axis_spindle->FirstChildElement("AbsZeroPos");
			m_Parameter.SpindleParam.AbsZeroPos = atol(ptr_spindle->GetText());

			ptr_spindle = p_axis_spindle->FirstChildElement("TransmissionRatio");
			m_Parameter.SpindleParam.TransmissionRatio = atof(ptr_spindle->GetText());

			ptr_spindle = p_axis_spindle->FirstChildElement("TorPdoMax");
			m_Parameter.SpindleParam.TorPdoMax = atoi(ptr_spindle->GetText());

			ptr_spindle = p_axis_spindle->FirstChildElement("AdditiveTor");
			m_Parameter.SpindleParam.AdditiveTorque = atoi(ptr_spindle->GetText());

			ptr_spindle = p_axis_spindle->FirstChildElement("MoveType");
			m_Parameter.SpindleParam.MoveType = atoi(ptr_spindle->GetText());

			ptr_spindle = p_axis_spindle->FirstChildElement("DriverType");
			m_Parameter.SpindleParam.DriverType = atoi(ptr_spindle->GetText());

			ptr_spindle = p_axis_spindle->FirstChildElement("Exposed");
			m_Parameter.SpindleParam.Exposed = bool(atoi(ptr_spindle->GetText()));

			ptr_spindle = p_axis_spindle->FirstChildElement("MaxVelocity");
			ptr_spindle = p_axis_spindle->FirstChildElement("MaxAcceleration");
			ptr_spindle = p_axis_spindle->FirstChildElement("MaxJerk");

			p_axis_spindle = p_axis_spindle->NextSiblingElement("axis");
		}
		p_axes_spindle = p_axes_spindle->NextSiblingElement("axes");
	}
	m_Parameter.CycleTime = static_cast<double>(m_TaskCycleTime) / 1E9;

	return (m_Parameter.SpindleParam.TorPdoMax < kEpsilon) ? S_FALSE : S_OK;
}

