///////////////////////////////////////////////////////////////////////////////
// ModuleSimulationServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_ModuleSimulation = 0x3F000000;
#define SRVNAME_MODULESIMULATION "ModuleSimulation"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ModuleSimulationCModuleSimulation = {0xfd1639f7,0xa08c,0x4b74,{0xa3,0xda,0x88,0x6f,0x84,0x40,0x0b,0x1e}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ModuleSimulationParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_05051960_DD0C_4E1E_BE19_8CF043C7E5C0_INCLUDED_)
#define _TC_TYPE_05051960_DD0C_4E1E_BE19_8CF043C7E5C0_INCLUDED_
typedef struct _DriverInput
{
	USHORT StatusWord;
	unsigned char reserved1[2];
	LONG ActualAbsPos;
	SHORT ActualTor;
	unsigned char reserved2[2];
	LONG ActualVel;
	SHORT ErrorCode;
	char ActualOpMode;
	unsigned char reserved3;
	SHORT EffectiveTorqueCmd;
	unsigned char reserved4[2];
	LONG EffectivePositionCmd;
	LONG EffectiveVelocityCmd;
} DriverInput, *PDriverInput;
#endif // !defined(_TC_TYPE_05051960_DD0C_4E1E_BE19_8CF043C7E5C0_INCLUDED_)

#if !defined(_TC_TYPE_344A141A_6449_48B1_917F_47644EE068F6_INCLUDED_)
#define _TC_TYPE_344A141A_6449_48B1_917F_47644EE068F6_INCLUDED_
typedef struct _DriverOutput
{
	USHORT ControlWord;
	unsigned char reserved1[2];
	LONG TargetPosition;
	SHORT TargetTorque;
	unsigned char reserved2[2];
	LONG TargetVelocity;
	char OperationMode;
	unsigned char reserved3;
	SHORT AdditiveTorque;
	LONG AdditiveVelocity;
	LONG AdditivePosition;
} DriverOutput, *PDriverOutput;
#endif // !defined(_TC_TYPE_344A141A_6449_48B1_917F_47644EE068F6_INCLUDED_)

#if !defined(_TC_TYPE_EE32EC38_3CFD_4D8B_9EB4_C1E6E69C354B_INCLUDED_)
#define _TC_TYPE_EE32EC38_3CFD_4D8B_9EB4_C1E6E69C354B_INCLUDED_
typedef struct _MotionControlInfo
{
	SHORT AbsEncDir;
	unsigned char reserved1[2];
	LONG AbsEncRes;
	double RatedCurrent;
	double RatedTorque;
	SHORT TorDir;
	unsigned char reserved2[2];
	LONG AbsZeroPos;
	double TransmissionRatio;
	SHORT TorPdoMax;
	SHORT AdditiveTorque;
	SHORT MoveType;
	SHORT DriverType;
	bool Exposed;
	unsigned char reserved3[7];
} MotionControlInfo, *PMotionControlInfo;
#endif // !defined(_TC_TYPE_EE32EC38_3CFD_4D8B_9EB4_C1E6E69C354B_INCLUDED_)

#if !defined(_TC_TYPE_3BD42FCA_85FC_C899_2F71_A9346CD54EAB_INCLUDED_)
#define _TC_TYPE_3BD42FCA_85FC_C899_2F71_A9346CD54EAB_INCLUDED_
typedef AmsNetId Tc2_System_T_AmsNetIdArr;
#endif // !defined(_TC_TYPE_3BD42FCA_85FC_C899_2F71_A9346CD54EAB_INCLUDED_)

#if !defined(_TC_TYPE_AF33319A_EDFA_B2D2_9FB8_D62638409ADE_INCLUDED_)
#define _TC_TYPE_AF33319A_EDFA_B2D2_9FB8_D62638409ADE_INCLUDED_
typedef struct _Tc2_EtherCAT_ST_PlcDriveRef
{
	Tc2_System_T_AmsNetIdArr aNetId;
	USHORT nSlaveAddr;
	BYTE nDriveNo;
	BYTE nDriveType;
} Tc2_EtherCAT_ST_PlcDriveRef, *PTc2_EtherCAT_ST_PlcDriveRef;
#endif // !defined(_TC_TYPE_AF33319A_EDFA_B2D2_9FB8_D62638409ADE_INCLUDED_)

#pragma pack(push,1)
typedef struct _ModuleSimulationParameter
{
	MotionControlInfo AxisGroupParam[10];
	MotionControlInfo SpindleParam;
	SHORT ActualAxisGroupDriverNum;
	double CycleTime;
} ModuleSimulationParameter, *PModuleSimulationParameter;
#pragma pack(pop)

typedef struct _ModuleSimulationInputs
{
	DriverOutput SimAxisGroupReceive[10];
	DriverOutput SimSpindleReceive;
} ModuleSimulationInputs, *PModuleSimulationInputs;

typedef struct _ModuleSimulationOutputs
{
	DriverInput SimAxisGroupTransmit[10];
	DriverInput SimSpindleTransmit;
	Tc2_EtherCAT_ST_PlcDriveRef SimAxisGroupDriverInfo[10];
} ModuleSimulationOutputs, *PModuleSimulationOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_ModuleSimulationInputs 0
#define ADI_ModuleSimulationOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
